AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'config.ru'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - Gemfile
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 22
Metrics/LineLength:
  Max: 130
  Exclude:
    - Rakefile
    - 'config/*'
Rails:
  Enabled: true
Rails/Delegate:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - Rakefile
    - '**/*.rake'