deploy:
  provider: heroku
  api_key:
    secure: fa3c4b26-90ef-46a0-b596-f8b4cc138bc7
  app:
    master: gymintel-staging
    production: gymintel
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"